/** Major Pakistani cities for address fields (master list). */
export const PAKISTANI_CITIES: string[] = [
  'Abbottabad',
  'Attock',
  'Badin',
  'Bahawalnagar',
  'Bahawalpur',
  'Bannu',
  'Bhalwal',
  'Burewala',
  'Chakwal',
  'Charsadda',
  'Chiniot',
  'Chishtian',
  'Dadu',
  'Dera Ghazi Khan',
  'Dera Ismail Khan',
  'Daska',
  'Faisalabad',
  'Gilgit',
  'Gojra',
  'Gujranwala',
  'Gujrat',
  'Gwadar',
  'Hafizabad',
  'Haripur',
  'Hasilpur',
  'Hub',
  'Hyderabad',
  'Islamabad',
  'Jacobabad',
  'Jaranwala',
  'Jhang',
  'Jhelum',
  'Kamalia',
  'Kamoke',
  'Karachi',
  'Kasur',
  'Khanewal',
  'Khanpur',
  'Kharian',
  'Khipro',
  'Khuzdar',
  'Kohat',
  'Kot Addu',
  'Kotli',
  'Lahore',
  'Larkana',
  'Layyah',
  'Lodhran',
  'Loralai',
  'Mandi Bahauddin',
  'Mansehra',
  'Mardan',
  'Mianwali',
  'Mingora',
  'Mirpur',
  'Mirpur Khas',
  'Multan',
  'Muzaffarabad',
  'Muzaffargarh',
  'Nawabshah',
  'Nowshera',
  'Okara',
  'Pakpattan',
  'Peshawar',
  'Quetta',
  'Rahim Yar Khan',
  'Rawalpindi',
  'Sahiwal',
  'Sargodha',
  'Sheikhupura',
  'Shikarpur',
  'Sialkot',
  'Skardu',
  'Sukkur',
  'Swabi',
  'Talagang',
  'Taxila',
  'Toba Tek Singh',
  'Turbat',
  'Umerkot',
  'Vehari',
  'Wah Cantonment',
  'Wazirabad',
]

export function isPakistaniCityField(
  validation: string,
  _fieldRef?: string,
  dataType?: string,
  fieldName?: string,
): boolean {
  const dt = (dataType ?? '').toLowerCase()
  const name = (fieldName ?? '').toLowerCase()
  if (dt.includes('phone') || name.includes('mobile') || name.includes('phone')) return false
  const v = validation.toLowerCase()
  return v.includes('master list of pakistani cit')
}

export function getPakistaniCities(search = ''): string[] {
  const term = search.trim().toLowerCase()
  if (!term) return [...PAKISTANI_CITIES]
  return PAKISTANI_CITIES.filter((city) => city.toLowerCase().includes(term))
}
